{{- if and .Values.apiServer.enabled .Values.apiServer.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rms-api-server
  namespace: {{ include "rack-manager.namespace" . }}
  labels:
    {{- include "rack-manager.labels" . | nindent 4 }}
    prometheus: {{ .Values.apiServer.serviceMonitor.prometheus }}
spec:
  selector:
    matchLabels:
      app: rms-api-server
  namespaceSelector:
    matchNames:
      - {{ include "rack-manager.namespace" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
      scheme: {{ if and .Values.apiServer.metrics.tls.enabled .Values.apiServer.tls.enabled }}https{{ else }}http{{ end }}
      {{- if and .Values.apiServer.metrics.tls.enabled .Values.apiServer.tls.enabled }}
      {{- $tlsCfg := .Values.apiServer.serviceMonitor.tlsConfig }}
      {{- if or $tlsCfg.insecureSkipVerify $tlsCfg.serverName $tlsCfg.caSecret }}
      tlsConfig:
        insecureSkipVerify: {{ $tlsCfg.insecureSkipVerify | default false }}
        {{- if $tlsCfg.serverName }}
        serverName: {{ $tlsCfg.serverName }}
        {{- end }}
        {{- if $tlsCfg.caSecret }}
        ca:
          secret:
            name: {{ $tlsCfg.caSecret }}
            key: {{ $tlsCfg.caSecretKey | default "ca.crt" }}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
