{{- if and .Values.apiServer.enabled .Values.apiServer.tls.enabled (not .Values.apiServer.tls.existingSecret) (ne (include "rack-manager.apiServerCertificateEnabled" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rack-manager.fullname" . }}-api-server-tls
  namespace: {{ include "rack-manager.namespace" . }}
  labels:
    {{- include "rack-manager.labels" . | nindent 4 }}
    app: rms-api-server
type: kubernetes.io/tls
data:
  tls.crt: {{ required "apiServer.tls.cert is required when TLS is enabled" .Values.apiServer.tls.cert | b64enc }}
  tls.key: {{ required "apiServer.tls.key is required when TLS is enabled" .Values.apiServer.tls.key | b64enc }}
  {{- if .Values.apiServer.tls.caEnabled }}
  ca.crt: {{ required "apiServer.tls.ca is required when caEnabled is true and TLS is enabled" .Values.apiServer.tls.ca | b64enc }}
  {{- end }}
{{- end }}
