{{- include "rack-manager.validateRmsPostgresKeys" . -}}
{{- $useRmsPostgres := eq (include "rack-manager.useRmsPostgres" .) "true" }}
{{- $patchEnabled := dig "patchExternalCluster" "enabled" false (.Values.rmsPostgres | default dict) }}
{{- if and .Values.createNamespace (not (and $useRmsPostgres $patchEnabled)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "rack-manager.namespace" . }}
  labels:
    name: {{ include "rack-manager.namespace" . }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
