{{- $sm := .Values.apiServer.serviceMonitor }}
{{- if and .Values.apiServer.enabled $sm.enabled .Values.apiServer.tls.enabled .Values.apiServer.tls.caEnabled $sm.clientCert.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-rms-client-tls
  namespace: {{ include "rack-manager.namespace" . }}
  labels:
    {{- include "rack-manager.labels" . | nindent 4 }}
spec:
  secretName: {{ $sm.clientCert.secretName }}
  duration: {{ $sm.clientCert.duration }}
  renewBefore: {{ $sm.clientCert.renewBefore }}
  subject:
    organizations:
      - prometheus
  commonName: prometheus
  usages:
    - client auth
  issuerRef:
    name: {{ $sm.clientCert.issuerName }}
    kind: {{ $sm.clientCert.issuerKind }}
    {{- if $sm.clientCert.issuerGroup }}
    group: {{ $sm.clientCert.issuerGroup }}
    {{- end }}
{{- end }}
